name: finvizor Node.js

on:
    push:
        branches: [main]
    pull_request:
        branches: [main, dev]
    schedule:
        - cron: '0 0 * * 5' # every Friday at 00:00 UTC

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['18', '20']
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm run build
            - run: npm test
